---
- name: Install mbpfan
  community.general.aur:
    name: mbpfan
    use: yay
    state: present
  become_user: "{{ target_user }}"

- name: Install mbpfan service override
  ansible.builtin.copy:
    src: /usr/lib/systemd/system/mbpfan.service
    dest: /etc/systemd/system/mbpfan.service
    remote_src: yes
    mode: '0644'

- name: Enable mbpfan
  ansible.builtin.systemd:
    name: mbpfan
    enabled: yes
    state: started
    daemon_reload: yes
