---
- name: Clone cros-keyboard-map
  ansible.builtin.git:
    repo: https://github.com/WeirdTreeThing/cros-keyboard-map.git
    dest: "{{ target_home }}/trees/cros-keyboard-map"
    update: no
  become_user: "{{ target_user }}"

- name: Install Chromebook F-keys
  ansible.builtin.command: ./install.sh
  args:
    chdir: "{{ target_home }}/trees/cros-keyboard-map"
